### PR TITLE
improving footer

### PR DESCRIPTION
**Pull request by kumarishalini6**
I have redesign the footer. 

Fixes#43

### CODE REVIEW

**Comment by CodesbyUnnati** [comment]
> I have redesign the footer.
> 
> Fixes#43

Can you attach the picture of the changes that you have done because I am not able to see any changes.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
Original:-

Elektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 3_19_2021 10_03_13 PM

Updated:-

Elektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 3_19_2021 10_01_23 PM

**Comment by kumarishalini6** [comment]
if still your not able to see the changes in code i can send another PR.

**Comment by CodesbyUnnati** [comment]
> if still your not able to see the changes in code i can send another PR.

Hey @kumarishalini6 The changes that you have made are not up to the level, The text under the logo looks very odd on the website. We do not have a channel, so we don't need subscribe now button, Also, the names are not looking good in capital.

**Comment by kumarishalini6** [comment]
ok

**Pull request closed without merging**
