### PR TITLE
icon

### PR DESCRIPTION
**Pull request by kumarishalini6**
Closes: #207 

#### Describe the changes you've made
I have added contact us icon at the home page
InkedElektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 5_23_2021 10_45_04 AM_LI

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khannakshat7 please review this PR

**Comment by khannakshat7** [comment]
@kumarishalini6 This PR doesn't look good to merge with current codebase. I have merged your other PRs

**Comment by kumarishalini6** [comment]
@khannakshat7  please merge this also

**Comment by kumarishalini6** [comment]
Ok then close this

**Comment by khannakshat7** [comment]
@kumarishalini6 If you can come up with something better than this it would be really great

**Pull request closed without merging**
