### PR TITLE
Contirbutor Updated 

### PR DESCRIPTION
**Pull request by rohank2502**
## Related Issuse

- Info about Issue or bug

Closes: #54 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

I have updated the read me section with the  automatically  updating contributor section !

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

### CODE REVIEW

**Comment by CodesbyUnnati** [comment]
Merged.

**Comment by CodesbyUnnati** [comment]
Merged.

**Comment by khannakshat7** [comment]
@rohank2502  Great contribution buddy!! 
Don't forget to star⭐ the repo and follow me on GitHub

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Great contribution buddy!!
> Don't forget to star⭐ the repo and follow me on GitHub

Sure @khannakshat7 @CodesbyUnnati

**Pull request merged**
