### PR TITLE
added issue and pr templates

### PR DESCRIPTION
**Pull request by Sloth-Panda**
issue : #15 

@khannakshat7

### CODE REVIEW

**Comment by khannakshat7** [comment]
@Sloth-Panda PR will be merged after we get guidelines from GS

**Comment by Sloth-Panda** [comment]
@khannakshat7  no issues but I see  prs are already getting merged in other projects under gssoc my 1pr has been merged too In another project

**Comment by CodesbyUnnati** [comment]
> @khannakshat7 no issues but I see prs are already getting merged in other projects under gssoc my 1pr has been merged too In another project anyways can you please add tags gssoc'21 to issue else they won't be counted

We'll look into your pull request ASAP.

**Comment by Sloth-Panda** [comment]
@khannakshat7 @CodesbyUnnati can you guys please review this pr?

**Review by CodesbyUnnati — APPROVED** [review]
Approved!

**Review by CodesbyUnnati — COMMENTED** [review]
Approved!

**Comment by Sloth-Panda** [comment]
please add the labels that are attached to the issue to the pr too else they are not getting counted @CodesbyUnnati

**Pull request merged**
