### PR TITLE
Added Error /Success messages in login and signup

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse
I have added Error and Success Message in sign up and log in 

Closes: #106 

#### Describe the changes you've made

https://drive.google.com/file/d/1w6xr6ih9F4xQSMvCIMzI268txKLGvhgk/view?usp=sharing

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@khannakshat7 kindly review my this PR and and my PR for feedback , it was ok from my side.


And may i format the login.html as it contains a lot of code its difficult to understand it. but if i format it it will show like whole file is changed that's why i asked before

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/116772053-0a8a7200-aa6b-11eb-97e0-de7a7f96296c.mp4

I forgot to show the password check here it is

**Comment by khannakshat7** [comment]
@arpit456jain I'll review it and merge

**Comment by arpit456jain** [comment]
> @arpit456jain I'll review it and merge

ok @khannakshat7 and please review  PR for Feedback

**Comment by khannakshat7** [comment]
@arpit456jain Good work buddy and sorry for the delay

**Pull request merged**
