### PR TITLE
Redirection issue of the logged in user.

### PR DESCRIPTION
**Pull request by pranjalg13**
After clicking in know more, if the user is already logged in it was still redirected to the signup/login page. I solved the issue by redirecting the user to the  #dashboard if he is logged in else if not then it is redirected to the login/signup page.
Solves #38

### CODE REVIEW

**Comment by pranjalg13** [comment]
@khannakshat7 Can you please check the PR?

**Comment by CodesbyUnnati** [comment]
Your PR's will be merged once we will get proper instructions...Please wait until that :)

**Comment by pranjalg13** [comment]
Ok Thanks.

**Comment by khannakshat7** [comment]
@pranjalg13 Great !!

**Comment by khannakshat7** [comment]
@pranjalg13  Great contribution !! 
Don't forget to star the repo and follow me on GitHub

**Pull request merged**
