### PR TITLE
#2-Acknowledging the user with future outrages : Worked on remote repo and modified it.#settings.py is also changed

### PR DESCRIPTION
**Pull request by SUMEKAGARWAL**
Modified the overall settings.py with accurate changes of mine and others as well.

### CODE REVIEW

**Comment by SUMEKAGARWAL** [comment]
Bhaiya, I have created a new PR and keenly modified every single thing this time.
Strongly hoping that there will not be any sort of mistake further.
Thank you. Regards.

**Comment by SUMEKAGARWAL** [comment]
Hello @khannakshat7, 
Is this sensable now?

**Comment by khannakshat7** [comment]
@SUMEKAGARWAL No issues dude I'll review and merge this PR soon

**Comment by SUMEKAGARWAL** [comment]
Thanks Bhaiya.
Glad to here that.

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 
Bhaiya, when will this PR be merged?

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 
Bhaiya when will this PR be merged?

**Comment by SUMEKAGARWAL** [comment]
Hello @khannakshat7 bhaiya,
When will this PR be merged?

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 
Sir, when will this PR will be merged?
Hoping for a reply.

**Comment by khannakshat7** [comment]
I'll review it and merge it soon

**Comment by SUMEKAGARWAL** [comment]
Hello @khannakshat7 ,
I heard that 31st is the last date of merging all the PRs. 
So could you please merge my PR as soon as possible. I really spent a lot and learnt a lot during this period. Thanks for the opportunity in advance.

Hope that my PR makes some difference to our website.

**Comment by khannakshat7** [comment]
@SUMEKAGARWAL Good Contribution !! sorry for the delay.

Don't forget to ⭐the repo and follow us on GitHub

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 Thanks for the encouragement!

**Pull request merged**
