### PR TITLE
added dark mode to the website

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

-added dark mode to the website

Closes: #170 
#### Describe the changes you've made

i am uploading a video

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://drive.google.com/file/d/1wwnpSow5W28LU9l50apBK10T5w0De9q0/view?usp=sharing

**Comment by khannakshat7** [comment]
@arpit456jain I can see that dark mode is implemented correctly. But the dark mode is not coming as expected like navbar is still white, Navbar is white, The cards should have grey or some other color. And we prefer a gray color than complete black.

**Comment by khannakshat7** [comment]
@arpit456jain You can also use some JS library to do this

**Comment by arpit456jain** [comment]
> @arpit456jain I can see that dark mode is implemented correctly. But the dark mode is not coming as expected like navbar is still white, Navbar is white, The cards should have grey or some other color. And we prefer a gray color than complete black.

Ok let me do some  more enhancements

**Comment by arpit456jain** [comment]
I had already add css for dark mode in dashboard.html 
Just need that js file which is in this PR

**Comment by arpit456jain** [comment]
> @arpit456jain You can also use some JS library to do this

@khannakshat7 no idea about it 😅

**Comment by arpit456jain** [comment]
@khannakshat7 you have to merge this PR so that i can rebase it and could do those enhancements you asked.
Please merge this PR .

I will make it perfect ASAP

**Comment by arpit456jain** [comment]
as soon this PR merged i will make a PR for dashboard its almost ready and in this PR i will all css to navbar and try to make it perfect as you want

**Comment by arpit456jain** [comment]
@khannakshat7 please merge this PR too . I had done the changes you requested in the PR for dashboard. Just waiting for merging this PR so that i can rebase my branch. 🙂

**Comment by arpit456jain** [comment]
Ok sure @khannakshat7 i will do this all in the PR for dashboard.

I had opened a issue for this please assign me

**Pull request merged**
