### PR TITLE
Dashboard issues - location access and hover

### PR DESCRIPTION
**Pull request by shivaamm**
## Related Issuse #63

- Info about Issue or bug
- In Dashboard only UDAIPUR, RAJASTHAN, INDIA location is visible, can't change the location.
- when we are on dashboard still home section is highlighted with blue color (kinda confusing when we are on dashboard section)

Closes: #63 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
1st - I suggested "We can add a dropdown feature from where we cana choose cities and later another dropdown box to choose exact place)", but I found even better solution to show the location of user using geolocation. It gives us country name, state, city also it provides log,lat and ip address related data but as we don't need them, I used only Country, State, City data.
2nd - Hover section and highlighted css issues can be solved by improving CSS.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation. (nothing to change in documentation)
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | 
image
<b>updated screenshot 
image
</b> |

### CODE REVIEW

**Comment by shivaamm** [comment]
I checked for other cities also it's working fine and giving the correct output :)

**Comment by khannakshat7** [comment]
@shivaamm Your contribution is good but can u just commit the changed files. Please remove settings.py file from ur commit.

**Comment by shivaamm** [comment]
> @shivaamm Your contribution is good but can u just commit the changed files. Please remove settings.py file from ur commit.

hey thanks!! So should I generate a new PR ?  you want the original settings.py file right?

**Comment by khannakshat7** [comment]
No just remove settings.py on this PR. No need to create new PR

**Review by shivaamm — COMMENTED** [review]
pls check now

**Comment by shivaamm** [comment]
Now only dashboard.html file is there with changes :)

**Comment by khannakshat7** [comment]
@shivaamm Great work!!

**Comment by shivaamm** [comment]
> @shivaamm Great work!!

Thanks!!

**Comment by khannakshat7** [comment]
@shivaamm Great contribution buddy!!
Don't forget to star⭐ the repo and follow us on GitHub

**Pull request merged**
