### PR TITLE
[GSSoC'21] Fixes the Responsiveness of map page 

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

Responsive ness of map page is very drastic it is looking like this
ele

Closes: #110 

#### Describe the changes you've made
I had just made the width of div to 100vw previously it was hard-code in pixels because of which it was creating problem.
 now it is looking like this
ele2

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by arpit456jain** [comment]
@khannakshat7 sir I had first pull the latest code and then make the changes I hope It will get merge very soon.
Please add labels which  are on my issue #110   specially Gssoc'21.
thank you.

**Comment by arpit456jain** [comment]
@khannakshat7 please review it.

**Comment by khannakshat7** [comment]
@arpit456jain Good Bug fix!!

**Comment by arpit456jain** [comment]
thank you @khannakshat7

**Pull request merged**
