### PR TITLE
feedback form

### PR DESCRIPTION
**Pull request by kumarishalini6**
The radio buttons were not working properly :-
I have removed the radio button error,

Describe the changes you've made
Firstly i have change style like:- text align-center , give some padding , margin and border shadow , and improve submit button and remove error present in form.
Fixes#44
Elektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 4_18_2021 01_57_49 PM
Elektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 4_18_2021 01_58_16 PM

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khannakshat7  now you can proceed please review it

**Comment by khannakshat7** [comment]
image
Please see there is a binary file in ur commit and settings.py remove them

**Comment by kumarishalini6** [comment]
ok

**Comment by khannakshat7** [comment]
@kumarishalini6 can u try manually deleting the files from commit

**Comment by kumarishalini6** [comment]
i am trying i don't know why it's not working

**Comment by kumarishalini6** [comment]
can you please guide me

**Comment by khannakshat7** [comment]
@kumarishalini6 Try searching for this issue on Google. Becoz I haven't seen this before.

**Comment by kumarishalini6** [comment]
ok

**Comment by kumarishalini6** [comment]
i 'll resend PR

**Pull request closed without merging**
