### PR TITLE
added contributing file

### PR DESCRIPTION
**Pull request by Sloth-Panda**
issue : #21 

@khannakshat7

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@khannakshat7  @CodesbyUnnati  can you guys review this pr?

**Review by CodesbyUnnati — APPROVED** [review]
Good!

**Comment by Sloth-Panda** [comment]
@CodesbyUnnati please add the labels  that are attached to the issue to the pr too else they are not getting counted

**Comment by khannakshat7** [comment]
@Sloth-Panda  Great contribution buddy!! 
Don't forget to star⭐ the repo and follow me on GitHub

**Pull request merged**
