### PR TITLE
Modified Elecktra- Issue:#68 "Acknowledging the user with future outrages."

### PR DESCRIPTION
**Pull request by SUMEKAGARWAL**
## Related Issuse

Added a new functionality of acknowledging the user about future outrages as a 8th block in feedback.html

Closes: #[68]

####Added a new funct
Screenshot (13)
ionality of acknowledging the user about future outrages as a 8th block in feedback.html

### CODE REVIEW

**Comment by SUMEKAGARWAL** [comment]
@CodesbyUnnati @khannakshat7 kindly review my pull request
Thank you 🙏🏻

**Comment by khannakshat7** [comment]
Error:
from electricity.forms import UserForm
ImportError: cannot import name 'UserForm'

You didn't commit forms.py file

**Comment by khannakshat7** [comment]
@SUMEKAGARWAL Bro u have commited ur Gmail password in settings.py file😂

No issues just change ur gmail password and remove from the commit.

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 Done.

**Comment by khannakshat7** [comment]
@SUMEKAGARWAL Bro u are not working on latest code run the code `git pull https://github.com/khannakshat7/Elektra.git master`

**Comment by khannakshat7** [comment]
Then create PR

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 Bhiaya, where to type this command?
I use VS code editor and its showing me error if I copy this url.
Can you please guide me.

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 Sorry bhai, dont mind! This is my first contribution.

**Comment by SUMEKAGARWAL** [comment]
@khannakshat7 Bro, I have created a new PR with the updates listed. Can you please have a look on that and notify me if I have to still do any changes?

**Pull request closed without merging**
