### PR TITLE
Added Feedback Model

### PR DESCRIPTION
**Pull request by sujoy-coder**
## Related Issuse

- added complete (frontend+backend both taken care of) `feedback` model 

Closes: #147 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by JAgrit20** [comment]
Your code looks good,
it won't take much time to do the required changes in the documentation, please do the needful

**Comment by sujoy-coder** [comment]
@JAgrit20 changes in the documentation means what I exactly need to do ?
Please help me :)

**Comment by sujoy-coder** [comment]
any update @khannakshat7 @JAgrit20 ??

**Comment by JAgrit20** [comment]
Let's do today together

**Comment by sujoy-coder** [comment]
Any update sir @JAgrit20 @khannakshat7 ??

**Comment by JAgrit20** [comment]
kindly message me on discord, my name is JAGRIT there ,in the Elektra channel you will find me

**Comment by khannakshat7** [comment]
@sujoy-coder Feedback model is already there pl. update ur fork

**Comment by sujoy-coder** [comment]
I will do it shortly. I am very busy for now

**Pull request closed without merging**
