### PR TITLE
Bug resolved in preloader

### PR DESCRIPTION
**Pull request by nikhilkotiya**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by nikhilkotiya** [comment]
@khannakshat7  bug is not removed in that code,  I just send a video to confirm preloader time,

**Comment by nikhilkotiya** [comment]
Checkout this code, just adding preloader time and remove nevbar.

**Comment by khannakshat7** [comment]
@nikhilkotiya can u add a good loading animation below the logo

**Comment by nikhilkotiya** [comment]
@khannakshat7 Sorry, i tried but i am not good at it and was not able to do it.

**Pull request merged**
