### PR TITLE
change password feature

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

change password feature implemented successfully.

Closes: #222 

#### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/119825529-aac1a280-bf14-11eb-8e0d-14aed5623089.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by arpit456jain** [comment]
@khannakshat7 please review the PR . I plan to  make a separate PR for  error / success msg  but i added this in this PR .
so kindly give lvl3 to this PR and my next PR for password validations in front-end and backend both

in next PR i will add password validations in front-end and backend both

**Comment by khannakshat7** [comment]
@arpit456jain In change password can u pl. ask for current password and validate it then change the password?

**Comment by khannakshat7** [comment]
There should be 3 inputs Current password, New password, Confirm password

**Comment by arpit456jain** [comment]
> There should be 3 inputs Current password, New password, Confirm password

@khannakshat7 no problem right now i am working on password validations i will make these changes in PR which i will create after this merged

**Pull request merged**
