### PR TITLE
added contact-form

### PR DESCRIPTION
**Pull request by tanishq-arya**
I have added the contact form in base.html and style changes in style.css

### CODE REVIEW

**Comment by tanishq-arya** [comment]
Okay. Thankyou for the update.

**Comment by khannakshat7** [comment]
@tanishq-arya We reviewed ur PR but we want some changes in it-
1. Increase the width of the form in mobile view to 90% or 95%. 
2. Remove the hover styling from the buttons. 
3. Also remove the other stylings that you have added to the homepage as this PR is only for the contact us form. You can create a different issue and make another PR for that.

**Comment by tanishq-arya** [comment]
Okay @khannakshat7 I'll get this done.

**Comment by tanishq-arya** [comment]
This is the final commit with only form added and no other changes.

**Comment by CodesbyUnnati** [comment]
> This is the final commit with only form added and no other changes.

image
you css file is not linked. Pl check.

**Comment by tanishq-arya** [comment]
On it.

**Comment by tanishq-arya** [comment]
@CodesbyUnnati  It's working on my side. I have made changes to the style.css only which was already linked to the base.html page.

**Comment by tanishq-arya** [comment]
What should I do now ? If I resolve any conflicts will it affect the new Contact page #69 ?

**Comment by CodesbyUnnati** [comment]
> What should I do now ? If I resolve any conflicts will it affect the new Contact page #69 ?

@khannakshat7  Pl look into it.

**Pull request closed without merging**
