### PR TITLE
Added a confirmation alert before logout

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

Added a confirmation alert before logout

Closes: #165 
#### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/116548422-d0f22380-a911-11eb-8888-8f2b9b16ece1.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by khannakshat7** [comment]
@arpit456jain Great Contribution dude !!

**Comment by khannakshat7** [comment]
@arpit456jain It is not working on Dashboard webpage as it is not inherited from base.html. Add the same code to dashboard.html

**Comment by arpit456jain** [comment]
> @arpit456jain It is not working on Dashboard webpage as it is not inherited from base.html. Add the same code to dashboard.html

Ok 👍

**Comment by arpit456jain** [comment]
@khannakshat7 kindly review my PR for feedback its pending from 10 days 😅

**Comment by khannakshat7** [comment]
ok I'll do that

**Comment by arpit456jain** [comment]
> @arpit456jain It is not working on Dashboard webpage as it is not inherited from base.html. Add the same code to dashboard.html

its done 👍

**Pull request merged**
