### PR TITLE
navbar

### PR DESCRIPTION
**Pull request by kumarishalini6**
Closes: #208 
I have improved the navbar items and add hover effect

https://user-images.githubusercontent.com/69043944/119252494-11cc0980-bb59-11eb-877f-a2f51bd535cf.mp4

### CODE REVIEW

**Comment by khannakshat7** [comment]
@kumarishalini6 Can you pl. change the style as it is not as per our theme

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/119384344-0966f200-bc71-11eb-843c-2d2ef748971d.mp4

**Comment by khannakshat7** [comment]
@kumarishalini6 pl. don't commit settings.py file

**Comment by kumarishalini6** [comment]
ok

**Comment by JAgrit20** [comment]
@khannakshat7  this looks good to me,
Please see it once and merge it
Thanks

**Pull request merged**
