### PR TITLE
Card

### PR DESCRIPTION
**Pull request by kumarishalini6**
Closes: #227 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by kumarishalini6** [comment]
Sorry but that repo deleted by me.

**Comment by kumarishalini6** [comment]
@khannakshat7 please review it

**Comment by kumarishalini6** [comment]
@khannakshat7  please review my PR

**Comment by JAgrit20** [comment]
Good work @kumarishalini6 ,
@khannakshat7  this looks good to go

**Comment by kumarishalini6** [comment]
@khannakshat7  please review my PR

**Pull request merged**
