### PR TITLE
New Login & Registration Form.

### PR DESCRIPTION
**Pull request by nikhilkotiya**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by khannakshat7** [comment]
@nikhilkotiya Pl. commit only those files which u have changed. Not all the files

**Comment by khannakshat7** [comment]
Don't change the DB name and other previous things. Only commit the files u have changed or added.

**Comment by nikhilkotiya** [comment]
@khannakshat7  Sir can you plz explain me how can i only commit on change file ? I changed my code in localhost and commit only those file which require

**Comment by nikhilkotiya** [comment]
@khannakshat7  Sir i am wating for 2 days but sakshi is not reply me , she dont know about static file so can i  create a frontend for login and sineup?

**Comment by khannakshat7** [comment]
@nikhilkotiya  use the command `git add <filename>` then `git commit -m "<name of the commit>"`

**Pull request closed without merging**
