### PR TITLE
Added recaptcha to contact form issue(#124)

### PR DESCRIPTION
**Pull request by ayushjha952**
## Related Issuse

- Added captcha in contact form

Closes: #[124]

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by khannakshat7** [comment]
@ayushjha952 Your Recaptcha is not implemented in the correct way. If u submit the form without ReCaptcha then also it is sending mail in the contact us form.

**Comment by ayushjha952** [comment]
But in my case if ReCaptcha  is giving error then I am not receiving and mail.

**Comment by ayushjha952** [comment]
@khannakshat7 Can you tell one thing why after commitng all commited code is getting erase from my local branch?

**Comment by ayushjha952** [comment]
@khannakshat7 now is it okay?

**Comment by ayushjha952** [comment]
@khannakshat7 I have added recaptcha to both can please check once?

**Comment by khannakshat7** [comment]
@ayushjha952 Great contribution buddy!! 🙌
This is one of the major contributions to this project.  We want more valuable contributions like this in the future.

**Comment by ayushjha952** [comment]
@khannakshat7 Thank you.
And for sure I will contribute more to this project.

**Pull request merged**
