### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by shonali2600**
## Related Issuse

Footer was not looking different from the whole page

Closes: #101 

#### Describe the changes you've made
I've designed the footer, changed the background colour and some of the text colour.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |
footer1

|         Updated           |
footer2

### CODE REVIEW

**Comment by shonali2600** [comment]
@khannakshat7 sir, @CodesbyUnnati ma'am, kindly review my PR and provide me feedback, it's been 7 days now.

**Comment by CodesbyUnnati** [comment]
image
This PR is having conflicts shonali...Pls resolve them:)
image
Also, Please maintain the color scheme of the website for the footer.

**Comment by shonali2600** [comment]
@CodesbyUnnati I've resolved the conflicts, and tried to change its color, but wasn't able to because of the "Elektra" Logo on the left side. I tried to use the blue color(same as Elektra logo) because it matches the theme, but the logo is not visible in that.
So can you please suggest me any better color?

**Comment by shonali2600** [comment]
@CodesbyUnnati @khannakshat7 Please suggest me changes so that I can work on it and able to make PR. Also my other PR are also pending since long #132 and #158 , Please review that also.

**Comment by khannakshat7** [comment]
@shonali2600 can you pl. resolve the conflicts

**Comment by shonali2600** [comment]
@khannakshat7 resolved the conflicts

**Comment by khannakshat7** [comment]
@shonali2600 Please don't use the beautifier and don't commit settings.py file as it has ur DB credentials

**Comment by shonali2600** [comment]
@khannakshat7 I've reverted the commit, now it's fine

**Comment by khannakshat7** [comment]
@shonali2600 It is perfect but can u pl. remove the extra space below footer.
image

**Comment by shonali2600** [comment]
elek

@khannakshat7 done

**Pull request merged**
