### PR TITLE
fix the responsiveness of preloader and copyright section in footer

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

Preloader  and footer is not responsive in small screen It was not looking so good.
It was looking like this
p5
 

Closes: #109 

#### Describe the changes you've made
I had made preloader and copy-right section in footer responsive in all screen
now it is looing like this. I hope you will like this.

https://user-images.githubusercontent.com/55352601/112027591-52a9a100-8b5d-11eb-9795-d444e8f52f37.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by arpit456jain** [comment]
@CodesbyUnnati  mam Please Review it I had not changed so much but now its looking better so doesn't make any problem.

**Comment by CodesbyUnnati** [comment]
> @CodesbyUnnati mam Please Review it I had not changed so much but now its looking better so doesn't make any problem.

Hey @arpit456jain I saw your PR, but we can't merge it at the moment because there is one person's PR whose code will be updated if we merged your code and he has to do the changes again, and the admin is really busy in some urgent work, so Pl wait till Friday, we will definitely look into it.

**Comment by arpit456jain** [comment]
ok mam no problem

**Comment by arpit456jain** [comment]
@CodesbyUnnati  mam I have a doubt
If someone's PR is got merged as you had told someone's PR is in queue.
Do i have to pull the latest code and had to do the changes again??

**Comment by arpit456jain** [comment]
@CodesbyUnnati  mam please review it Its been 3 days.

**Comment by arpit456jain** [comment]
> > @CodesbyUnnati mam Please Review it I had not changed so much but now its looking better so doesn't make any problem.
> 
> Hey @arpit456jain I saw your PR, but we can't merge it at the moment because there is one person's PR whose code will be updated if we merged your code and he has to do the changes again, and the admin is really busy in some urgent work, so Pl wait till Friday, we will definitely look into it.

@CodesbyUnnati mam Its Friday now Please Review it.

**Comment by khannakshat7** [comment]
@arpit456jain Your logo size on desktop screen is not correct, It is too big. Change the size of logo back to original and also center it to the screen both vertically and horizontally.

**Comment by arpit456jain** [comment]
> @arpit456jain Your logo size on desktop screen is not correct, It is too big. Change the size of logo back to original and also center it to the screen both vertically and horizontally.

@khannakshat7  Sir It's already like that I haven't changed it 
I just changed this . so that overflow of image can be solved that's it.
elecktra

**Comment by khannakshat7** [comment]
@arpit456jain Pl. pull the code from master branch and see the current code.

**Comment by arpit456jain** [comment]
Its was my 2nd issue when I just started contributions.
My  issue was very small **level0 or level 1**

@khannakshat7 sir you want I can work on responsiveness of the website but for that I will create a new separate issue in which I will work on whole website.

It was just a small issue please merge it if possible .

**Comment by arpit456jain** [comment]
> @arpit456jain Pl. pull the code from master branch and see the current code.

ok sir 1 min

**Comment by arpit456jain** [comment]
Give me 5 min

**Comment by arpit456jain** [comment]
yes sir I had pull  the latest code it is looking like this the logo is still very large. but its ok for now .

https://user-images.githubusercontent.com/55352601/112712845-f5647580-8ef7-11eb-9d89-78e9764a7c17.mp4

**Comment by arpit456jain** [comment]
> @arpit456jain Please clone the repo again in some temp location and see

ok sir give me 5 min

**Comment by arpit456jain** [comment]
@khannakshat7  yes sir Its fine my fault. You can close issue #109 and this PR

but @khannakshat7 sir The map is still not responsive in phone view 
I had open a issue 5 or 6 days ago #110 and it was assigned to me .
It is still here. I am uploading a video Kindly watch it video and skip 2-3 min from start.

If you get it right , I will make it work properly now .

**Comment by arpit456jain** [comment]
sir please wait some time video is taking more time than expected.

**Comment by khannakshat7** [comment]
@arpit456jain Bro u can commit on the same PR no need to close it.

**Comment by arpit456jain** [comment]
@khannakshat7 sir I had cloned it and now i am on a new branch how can I commit on this PR.?


https://user-images.githubusercontent.com/55352601/112714326-dd90ef80-8eff-11eb-9ad0-cbdbf0631748.mp4


There is a already a separate issue for responsiveness of map so thought I can create a new PR there and close this.

**Comment by arpit456jain** [comment]
> sir please wait some time video is taking more time than expected.

video is uploaded you can see the problem it in last 1 min of video.

**Comment by arpit456jain** [comment]
@khannakshat7 sir i am more comfortable in creating a new PR ,
on issue #110 
If you allow me.

**Pull request closed without merging**
