### PR TITLE
Fixed the bug in Feedback and Added the Backend for it

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

I will make a video for this

Closes: #157 

#### Describe the changes you've made

this will also in video

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@khannakshat7 @CodesbyUnnati kindly review my PR this is video url 
https://drive.google.com/file/d/1OpbOMgyheaNPLCxVdaBcce_fE1L9E3ZA/view?usp=sharing

the problem and sol

**Comment by arpit456jain** [comment]
after my last commit


https://user-images.githubusercontent.com/55352601/115593817-9d504180-a2f2-11eb-96cd-1468bef923d3.mp4

**Comment by arpit456jain** [comment]
@khannakshat7 kindly add labels to this PR which are on issue ie level 3

**Comment by khannakshat7** [comment]
@arpit456jain I'll review it and merge soon

**Comment by khannakshat7** [comment]
@arpit456jain When I'm filling the form with correct values then after submit it is showing  "Please Fill FeedBack Properly !!"

Please check for the mistake

**Comment by arpit456jain** [comment]
> @arpit456jain When I'm filling the form with correct values then after submit it is showing "Please Fill FeedBack Properly !!"
> 
> Please check for the mistake

Ok let me check

**Comment by arpit456jain** [comment]
@khannakshat7 did you run the command

Py.exe manage.py makemigrations 

And the migrate

Because i have made a new table in db may be that's why its showing error because in my local system its running fine

**Comment by arpit456jain** [comment]
@khannakshat7 its working 100% correct from my side i  am uploading a video for the same 

https://drive.google.com/file/d/1viB543M6M-u-eq1MIYM8Y8kWv8ITlHYP/view?usp=sharing

**Comment by arpit456jain** [comment]
Please Try again after making necessary changes to Database

**Comment by arpit456jain** [comment]
> @khannakshat7 did you run the command
> 
> Py.exe manage.py makemigrations
> 
> And the migrate
> 
> Because i have made a new table in db may be that's why its showing error because in my local system its running fine

@khannakshat7 please review this PR its been 15 days and this PR is working properly from ny side please run migration commands before checking

**Comment by khannakshat7** [comment]
@arpit456jain Great contribution!! Sorry for the late response. I was busy with some work.

**Comment by arpit456jain** [comment]
> @arpit456jain Great contribution!! Sorry for the late response. I was busy with some work.

No problem thanks 🙂

**Pull request merged**
