### PR TITLE
improving feedback form

### PR DESCRIPTION
**Pull request by kumarishalini6**
**The radio buttons were not working properly** :-
 I have removed the radio button error,

### Describe the changes you've made

Firstly i have change style like:- text align-center , give some padding , margin and border shadow , and improve submit button and remove error present in form.
Fixes#44

### CODE REVIEW

**Comment by CodesbyUnnati** [comment]
which radio button error are you talking about? The stars?

**Comment by kumarishalini6** [comment]
yes, the start was not working properly ,

**Comment by kumarishalini6** [comment]
because you gave same name in each input that's why while felling form if we filled one star and went to fill other , the first one  remove automatically 
<input type="radio" name="rating" value="1">
                    <input type="radio" **name="rating"** value="2">
                    <input type="radio" **name="rating"** value="3">

**Comment by kumarishalini6** [comment]
When my PR got merged

**Comment by CodesbyUnnati** [comment]
> When my PR got merged

BY EOD

**Comment by CodesbyUnnati** [comment]
> > When my PR got merged
> 
> BY EOD

@khannakshat7 Pl review this PR.

**Comment by kumarishalini6** [comment]
please review my PR

**Comment by kumarishalini6** [comment]
I have solve the conflicts , Now can you please check the PR

**Comment by kumarishalini6** [comment]
Please review my PR 26 days is too long

**Comment by JAgrit20** [comment]
@khannakshat7,  please review this and merge it ASAP

**Comment by khannakshat7** [comment]
@kumarishalini6 Few changes that are required- 
1. Pl. don't commit settings.py file
2. why have u created feedback2.html file? (Make changes in the original file only)
3. In changed files I can see an unwanted "Elektra " Binary file. What is that?

**Comment by kumarishalini6** [comment]
ok i'll all the changes

**Comment by khannakshat7** [comment]
@kumarishalini6 I can see some binary files in changed files can u pl. manually remove them? 
Then I'll quickly merge the PR

**Comment by kumarishalini6** [comment]
@khannakshat7 i am going to close this PR and resend PR on this issue

**Comment by khannakshat7** [comment]
ok

**Pull request closed without merging**
