### PR TITLE
placed forgot password to the right place and fixed the typo

### PR DESCRIPTION
**Pull request by shonali2600**
## Related Issuse

-there was a typo in forgot password as well as it was placed with sign up instead of login

Closes: #100 

#### Describe the changes you've made

I've placed forgot password to the right place along with fixed its typo

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |  
|
elektra

|        Updated           |
elektra2

### CODE REVIEW

**Comment by khannakshat7** [comment]
@shonali2600 Pl. don't commit ur settings.py file

**Comment by shonali2600** [comment]
@khannakshat7 sir, I'm trying to uncommit settings.py and commit the only login.html, but I'm getting an error.
Can I make another branch for it?

**Comment by khannakshat7** [comment]
ok try to do that

**Comment by shonali2600** [comment]
sir I created a Pull request #132 using another branch, sir please review that.

**Comment by khannakshat7** [comment]
Duplicate of #132

**Pull request closed without merging**
