### PR TITLE
Imroving SignIn, SignUp, feedback form

### PR DESCRIPTION
**Pull request by kumarishalini6**
Closes: #227 
I have improve the forms by giving background color , shadow in form and in the input like:--
Elektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 5_28_2021 11_17_12 PM

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khannakshat7 please have a look on this issue

**Comment by JAgrit20** [comment]
Looks good, @kumarishalini6 
@khannakshat7, i don't see and issues in this

**Comment by khannakshat7** [comment]
@kumarishalini6 good contribution just a little change can u pl. update ur fork / code and then make a commit as you are not working on new code.
Do this I'll merge it quickly

**Comment by kumarishalini6** [comment]
i have send  it again

**Pull request closed without merging**
