### PR TITLE
Email warning if login fails more than 5 times 

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

Email warning if login fails more than 5 times 

Closes: #206 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by arpit456jain** [comment]
@khannakshat7 you can check my feature its working very well and its very optimized

**Comment by arpit456jain** [comment]
@khannakshat7  please review this PR

**Comment by khannakshat7** [comment]
@arpit456jain I'll merge it by tomorrow

**Comment by arpit456jain** [comment]
@khannakshat7 is this feature working fine?

**Pull request merged**
