### PR TITLE
login updated

### PR DESCRIPTION
**Pull request by sreetu**
## Related Issuse

- Info about Issue or bug
In the login section, if one does not fill the details like email and password and click on submit then, it is redirecting to the next webpage.

Closes: #166[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

I have added the mandatory field option in login.html file for the required inputs.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by sreetu** [comment]
Requesting @admins to review my PR.

Screenshot (615)

**Comment by khannakshat7** [comment]
@sreetu Can u pl check why it is showing all lines changed. Pl. fix that in changed files of ur PR

**Comment by khannakshat7** [comment]
@sreetu I think ur fork is not updated. Please work on latest code.

**Comment by khannakshat7** [comment]
And resolve the conflicts

**Comment by sreetu** [comment]
Sir, I have updated my fork twice but the conflicted code does not arise there. I am working on it.

**Comment by sreetu** [comment]
@khannakshat7 sir, after resolving conflict, when i try to merge the resolved conflict by clicking on commit merge (to commit the changes in pr) and updating changes to master branch, it everytime mentions that all lines are changed. what should i do next?

**Comment by sreetu** [comment]
Actually Sir, while resolving conflict some changes are made on github editor then, while commiting those changes, the whole file gets committed again, that's why, it says that all lines changed.

**Comment by arpit456jain** [comment]
> Actually Sir, while resolving conflict some changes are made on github editor then, while commiting those changes, the whole file gets committed again, that's why, it says that all lines changed.

I suggest you to make a fresh PR. As i also go through this type of problems many times.

As much i understand you just have to put ''required" in two input tags...so its not a big deal to do this changes again. Just pull the latest code in master branch to your master.make a new branch, do the changes, make a fresh PR simple

**Comment by sreetu** [comment]
Ok

**Pull request closed without merging**
