### PR TITLE
added username and email checking in front end

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issuse

The clear description of issue  and solution  is in video i can't explain it by only writing

Closes: #160 

#### Describe the changes you've made

watch the video carefully ! 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

here is the video for problem and solution
https://drive.google.com/file/d/1kcDaVY4Vm8TZxnu8ioU0u9u9k11a4RXa/view?usp=sharing

### CODE REVIEW

**Comment by arpit456jain** [comment]
@khannakshat7 kindly review my PR

**Comment by khannakshat7** [comment]
@arpit456jain Great work buddy !!! This is an awesome contribution to the project

**Comment by arpit456jain** [comment]
> @arpit456jain Great work buddy !!! This is an awesome contribution to the project

Thanks @khannakshat7 .


I would love to add dark mode to website i have commented many times if possible assign me that issue

**Comment by khannakshat7** [comment]
ok I'll look into it.

**Comment by khannakshat7** [comment]
> > @arpit456jain Great work buddy !!! This is an awesome contribution to the project
> 
> Thanks @khannakshat7 .
> 
> I would love to add dark mode to website i have commented many times if possible assign me that issue

Can u tell me which issue?

**Comment by arpit456jain** [comment]
> > > @arpit456jain Great work buddy !!! This is an awesome contribution to the project
> > 
> > 
> > Thanks @khannakshat7 .
> > I would love to add dark mode to website i have commented many times if possible assign me that issue
> 
> Can u tell me which issue?

#95 

and there are two more issue opened for the same the recently one is #170

**Comment by arpit456jain** [comment]
@khannakshat7

**Pull request merged**
