### PR TITLE
added welcome bot

### PR DESCRIPTION
**Pull request by Sloth-Panda**
issue: #14 

@khannakshat7

### CODE REVIEW

**Comment by khannakshat7** [comment]
@Sloth-Panda PR will be merged after we get guidelines from GS

**Comment by Sloth-Panda** [comment]
@khannakshat7 no issues please add the tags to the issue

**Comment by Sloth-Panda** [comment]
@khannakshat7 @CodesbyUnnati please review this one

**Comment by Sloth-Panda** [comment]
please add the labels that are attached to the issue to the pr too else they are not getting counted @CodesbyUnnati

**Comment by khannakshat7** [comment]
@Sloth-Panda  Great contribution buddy!! 
Don't forget to star the repo and follow me on GitHub

**Pull request merged**
